# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-eu2'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloateu2'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-eaus'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgo-float-eaus_group'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-asea'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgoflaotasea'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-apac3'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloatapac3'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-apac4'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloatapac4'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-auea'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloatauea'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-br'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloatbr'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-cace'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloatcace'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-eaus-2'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloateaus2'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-eu4'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloateu-4'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-eu4'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloateu-4'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-eu1'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloateu1'
    verbose: true
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'MSFree'
    appType: functionAppLinux
    appName: 'csgo-float-eu3'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'
    deploymentMethod: 'zipDeploy' 
    resourceGroupName: 'csgofloateu3'
